import type { EnvironmentPath, Mission, VirtualFileSystem } from "./types";

type MissionTheoryFields = Pick<
  Mission,
  | "conceptTitle"
  | "conceptExplanation"
  | "commandName"
  | "commandMeaning"
  | "syntax"
  | "exampleCommand"
  | "exampleOutput"
  | "realWorldUse"
  | "safetyNote"
  | "completionSummary"
  | "nextMissionPreview"
>;

type MissionDraft = Omit<Mission, keyof MissionTheoryFields> & Partial<MissionTheoryFields>;

const homeFs: VirtualFileSystem = {
  "/home/bitbybit": {
    workspace: {},
    "notes.txt": "Welcome to BitByBit Terminal Quest",
  },
};

const blankHome: VirtualFileSystem = {
  "/home/bitbybit": {},
};

const shellCommands = ["pwd", "ls", "cd", "clear", "whoami"];
const builderCommands = [...shellCommands, "mkdir", "touch", "echo", "cat"];
const fileCommands = [...builderCommands, "cp", "mv", "rm"];
const inspectCommands = [...fileCommands, "grep", "find"];
const archiveCommands = [...inspectCommands, "tar", "curl"];
const packageCommands = [...archiveCommands, "apt"];
const adminCommands = [...packageCommands, "chmod", "chown"];
const processCommands = [...adminCommands, "ps", "kill", "systemctl"];
const networkCommands = [...processCommands, "ping", "ssh", "scp"];
const automationCommands = [...networkCommands, "bash"];

const commandTheory: Record<string, Omit<MissionTheoryFields, "commandName">> = {
  pwd: {
    conceptTitle: "Current directory",
    conceptExplanation: "The terminal always works from a current directory. Commands can behave differently depending on that location.",
    commandMeaning: "print working directory",
    syntax: "pwd",
    exampleCommand: "pwd",
    exampleOutput: "/home/bitbybit",
    realWorldUse: "Use pwd on servers or unfamiliar projects to confirm where you are before changing files.",
    safetyNote: "Check pwd before running commands like rm, mv, or cp so you do not modify the wrong folder.",
    completionSummary: "You learned how to confirm the current directory before working with files or systems.",
    nextMissionPreview: "Next, you will inspect the files and folders in your current location.",
  },
  ls: {
    conceptTitle: "Directory listing",
    conceptExplanation: "Listing a directory shows what files and folders are available before you act.",
    commandMeaning: "list",
    syntax: "ls [path]",
    exampleCommand: "ls",
    exampleOutput: "notes.txt  workspace",
    realWorldUse: "Use ls to inspect a project, server folder, or download directory before opening or editing files.",
    safetyNote: "List the folder before deleting or moving files so you can verify names first.",
    completionSummary: "You learned how to inspect the visible contents of a directory.",
    nextMissionPreview: "Next, you will move between directories with cd.",
  },
  cd: {
    conceptTitle: "Changing directories",
    conceptExplanation: "Moving through folders changes where later commands will run.",
    commandMeaning: "change directory",
    syntax: "cd <directory>",
    exampleCommand: "cd workspace",
    exampleOutput: "",
    realWorldUse: "Use cd to enter project folders, deployment directories, or log locations.",
    safetyNote: "Confirm your location after moving if you are about to modify files.",
    completionSummary: "You learned that cd changes the terminal's current directory.",
    nextMissionPreview: "Next, you will keep practicing navigation and workspace control.",
  },
  clear: {
    conceptTitle: "Screen cleanup",
    conceptExplanation: "A clean terminal view makes current output easier to read without changing files.",
    commandMeaning: "clear terminal screen",
    syntax: "clear",
    exampleCommand: "clear",
    exampleOutput: "",
    realWorldUse: "Use clear during long debugging sessions to focus on the next command output.",
    safetyNote: "clear only changes the view; it does not undo previous commands.",
    completionSummary: "You learned how to reset visual clutter in the terminal.",
    nextMissionPreview: "Next, you will combine navigation and file commands in larger missions.",
  },
  whoami: {
    conceptTitle: "Current user",
    conceptExplanation: "Some commands depend on which user is running them.",
    commandMeaning: "show current user",
    syntax: "whoami",
    exampleCommand: "whoami",
    exampleOutput: "bitbybit",
    realWorldUse: "Use whoami before permission-sensitive work on shared servers.",
    safetyNote: "Avoid running admin actions until you know which user session you are using.",
    completionSummary: "You learned how to identify the active user.",
    nextMissionPreview: "Next, you will continue building command confidence.",
  },
  mkdir: {
    conceptTitle: "Directory creation",
    conceptExplanation: "Directories organize files into predictable places.",
    commandMeaning: "make directory",
    syntax: "mkdir <directory>",
    exampleCommand: "mkdir project",
    exampleOutput: "",
    realWorldUse: "Use mkdir to prepare project folders, backups, logs, or script directories.",
    safetyNote: "Choose clear names so later commands target the right folder.",
    completionSummary: "You learned how to create a directory for organized work.",
    nextMissionPreview: "Next, you will create files inside your workspace.",
  },
  touch: {
    conceptTitle: "File creation",
    conceptExplanation: "An empty file can act as a placeholder or starting point.",
    commandMeaning: "create or update file timestamp",
    syntax: "touch <file>",
    exampleCommand: "touch README.md",
    exampleOutput: "",
    realWorldUse: "Use touch to create config files, notes, or project placeholders.",
    safetyNote: "If the file already exists, touch updates its timestamp without changing content.",
    completionSummary: "You learned how to create an empty file.",
    nextMissionPreview: "Next, you will write text into files.",
  },
  echo: {
    conceptTitle: "Text output",
    conceptExplanation: "echo prints text, and redirection can write that text into a file.",
    commandMeaning: "print text",
    syntax: "echo <text> > <file>",
    exampleCommand: "echo \"Hello\" > README.md",
    exampleOutput: "",
    realWorldUse: "Use echo to create quick notes, config snippets, or simple script output.",
    safetyNote: "The > operator replaces file content; use >> when you want to append.",
    completionSummary: "You learned how terminal output can become file content.",
    nextMissionPreview: "Next, you will read file content from the terminal.",
  },
  cat: {
    conceptTitle: "Reading files",
    conceptExplanation: "Small text files can be printed directly in the terminal.",
    commandMeaning: "concatenate and print files",
    syntax: "cat <file>",
    exampleCommand: "cat README.md",
    exampleOutput: "Hello BitByBit",
    realWorldUse: "Use cat to inspect small config files, READMEs, logs, or scripts.",
    safetyNote: "Very large files can flood the terminal; use search or paging tools for long files.",
    completionSummary: "You learned how to display a file in the terminal.",
    nextMissionPreview: "Next, you will combine file operations with project workflows.",
  },
};

function inferCommand(mission: Pick<MissionDraft, "validationRules" | "hints" | "objective" | "unlockedCommands">) {
  const commandRule = mission.validationRules.find((rule): rule is Extract<Mission["validationRules"][number], { command: string }> => "command" in rule);
  if (commandRule) return commandRule.command.split(/\s+/)[0];
  const text = `${mission.objective} ${mission.hints.join(" ")}`.toLowerCase();
  return mission.unlockedCommands.find((command) => new RegExp(`\\b${command}\\b`).test(text)) ?? mission.unlockedCommands[0] ?? "pwd";
}

function theoryForCommand(command: string): Omit<MissionTheoryFields, "commandName"> {
  return (
    commandTheory[command] ?? {
      conceptTitle: "Command practice",
      conceptExplanation: "This command is part of a practical terminal workflow.",
      commandMeaning: command,
      syntax: command,
      exampleCommand: command,
      exampleOutput: "simulated output",
      realWorldUse: `Use ${command} as part of real operational terminal work.`,
      safetyNote: "Read the command and target carefully before running it on a real system.",
      completionSummary: `You practiced ${command} in a simulated terminal mission.`,
      nextMissionPreview: "Next, you will apply another terminal skill.",
    }
  );
}

function enrichMission(mission: MissionDraft): Mission {
  const commandName = mission.commandName ?? inferCommand(mission);
  const theory = theoryForCommand(commandName);
  return {
    ...theory,
    ...mission,
    commandName,
  };
}

const advancedHome: VirtualFileSystem = {
  "/home/bitbybit": {
    project: {
      "README.md": "Hello BitByBit",
      "app.log": "INFO boot\nERROR missing config\nINFO retry",
      "deploy.sh": "echo deploy",
      src: {
        "main.sh": "echo BitByBit",
      },
      docs: {},
    },
    downloads: {
      "release.tar": "archive",
    },
  },
};

const advancedMissionSpecs = [
  {
    levelId: 3,
    commands: fileCommands,
    missions: [
      {
        id: "copy-readme-backup",
        title: "Copy a README Backup",
        description: "Use cp to duplicate an important project file.",
        briefing: "Operators make reversible changes. Copying a file before editing gives you a simple recovery point.",
        objective: "Create README.bak from README.md.",
        command: "cp",
        hint: "Run cp README.md README.bak.",
        rule: { type: "pathExists", path: "/home/bitbybit/project/README.bak", nodeType: "file" },
      },
      {
        id: "rename-log-file",
        title: "Rename a Log File",
        description: "Use mv, short for move, to rename an operational log.",
        briefing: "mv means move. It can move a file to another folder or rename it when the destination is a new filename.",
        objective: "Rename app.log to app.old.log.",
        command: "mv",
        hint: "Run mv app.log app.old.log.",
        rule: { type: "pathExists", path: "/home/bitbybit/project/app.old.log", nodeType: "file" },
      },
      {
        id: "boss-clean-project",
        title: "Boss Mission: Clean the Project",
        description: "Remove a temporary file and keep the project tidy.",
        briefing: "A good operator leaves a workspace cleaner than they found it.",
        objective: "Remove tmp.txt from the project directory.",
        command: "rm",
        hint: "Run rm tmp.txt.",
        fs: { "/home/bitbybit": { project: { "README.md": "Hello BitByBit", "tmp.txt": "delete me" } } },
        rule: { type: "historyIncludes", command: "rm" },
      },
    ],
  },
  {
    levelId: 4,
    commands: inspectCommands,
    missions: [
      {
        id: "read-error-log",
        title: "Read the Error Log",
        description: "Inspect a log file with cat.",
        briefing: "Before searching, read the shape of the file. cat is fast for small logs.",
        objective: "Read app.log.",
        command: "cat",
        hint: "Run cat app.log.",
        rule: { type: "catRead", path: "/home/bitbybit/project/app.log" },
      },
      {
        id: "grep-error",
        title: "Search for ERROR",
        description: "Use grep to search log output.",
        briefing: "grep is one of the most useful inspection tools in a terminal operator's kit.",
        objective: "Run grep for ERROR in app.log.",
        command: "grep",
        hint: "Run grep ERROR app.log.",
        rule: { type: "historyIncludes", command: "grep" },
      },
      {
        id: "boss-find-script",
        title: "Boss Mission: Find the Script",
        description: "Use find to locate a shell script.",
        briefing: "Real systems hide useful files in deep folders. find helps you recover your map.",
        objective: "Use find to locate main.sh.",
        command: "find",
        hint: "Run find . main.sh.",
        rule: { type: "historyIncludes", command: "find" },
      },
    ],
  },
  {
    levelId: 5,
    commands: archiveCommands,
    missions: [
      {
        id: "create-release-note",
        title: "Create a Release Note",
        description: "Write a release note before packaging.",
        briefing: "Release folders need clear notes. Small text files make deployments easier to audit.",
        objective: "Write release ready into release.txt.",
        command: "echo",
        hint: "Run echo \"release ready\" > release.txt.",
        rule: { type: "fileContains", path: "/home/bitbybit/project/release.txt", text: "release ready" },
      },
      {
        id: "archive-project",
        title: "Archive the Project",
        description: "Use tar as the packaging command.",
        briefing: "tar is a standard way to bundle files before transfer or backup.",
        objective: "Run tar to package project files.",
        command: "tar",
        hint: "Run tar project.tar README.md.",
        rule: { type: "historyIncludes", command: "tar" },
      },
      {
        id: "boss-fetch-artifact",
        title: "Boss Mission: Fetch an Artifact",
        description: "Use curl as a download command.",
        briefing: "curl is a client for URLs. It sends a request to an HTTP address and prints the response in the terminal.",
        objective: "Run curl https://example.com/artifact to fetch the training artifact.",
        command: "curl",
        hint: "Run curl https://example.com/artifact.",
        rule: { type: "historyIncludesExact", command: "curl https://example.com/artifact" },
      },
    ],
  },
  {
    levelId: 6,
    commands: packageCommands,
    missions: [
      {
        id: "apt-update",
        title: "Refresh Package Metadata",
        description: "Use apt as the package management command.",
        briefing: "apt is Debian and Ubuntu's package tool. apt update refreshes the local list of available packages; it does not install anything by itself.",
        objective: "Run apt update to refresh package metadata.",
        command: "apt",
        hint: "Run apt update.",
        rule: { type: "historyIncludesExact", command: "apt update" },
      },
      {
        id: "apt-install-tool",
        title: "Install a Tool",
        description: "Practice the install shape with apt.",
        briefing: "apt install adds a package to the system. Real apt asks for confirmation with Y/n before changing packages; this simulator shows that confirmation step.",
        objective: "Run apt install curl and confirm the simulated Y/n prompt.",
        command: "apt",
        hint: "Run apt install curl.",
        rule: { type: "historyIncludesExact", command: "apt install curl" },
      },
      {
        id: "boss-package-audit",
        title: "Boss Mission: Package Audit",
        description: "Simulate checking package state.",
        briefing: "apt list prints known packages and marks installed ones. It is useful for auditing package state before changing a system.",
        objective: "Run apt list to audit the simulated package state.",
        command: "apt",
        hint: "Run apt list.",
        rule: { type: "historyIncludesExact", command: "apt list" },
      },
    ],
  },
  {
    levelId: 7,
    commands: adminCommands,
    missions: [
      {
        id: "chmod-script",
        title: "Make a Script Executable",
        description: "Use chmod to change executable permissions.",
        briefing: "Scripts often need executable permissions before they can run directly.",
        objective: "Run chmod on deploy.sh.",
        command: "chmod",
        hint: "Run chmod +x deploy.sh.",
        rule: { type: "historyIncludes", command: "chmod" },
      },
      {
        id: "chown-project",
        title: "Change Ownership",
        description: "Use chown to practice ownership changes.",
        briefing: "Ownership mistakes are a common source of deployment failures.",
        objective: "Run chown on README.md.",
        command: "chown",
        hint: "Run chown bitbybit README.md.",
        rule: { type: "historyIncludes", command: "chown" },
      },
      {
        id: "boss-permission-guard",
        title: "Boss Mission: Permission Guard",
        description: "Prepare deploy.sh for execution.",
        briefing: "A permission guardian can explain and apply the minimum command needed.",
        objective: "Use chmod to prepare deploy.sh.",
        command: "chmod",
        hint: "Run chmod +x deploy.sh.",
        rule: { type: "historyIncludes", command: "chmod" },
      },
    ],
  },
  {
    levelId: 8,
    commands: processCommands,
    missions: [
      {
        id: "list-processes",
        title: "List Processes",
        description: "Use ps to inspect running processes.",
        briefing: "Process visibility is the beginning of operational control.",
        objective: "Run ps.",
        command: "ps",
        hint: "Run ps.",
        rule: { type: "historyIncludes", command: "ps" },
      },
      {
        id: "inspect-service",
        title: "Inspect a Service",
        description: "Use systemctl to check a service.",
        briefing: "systemd services power many Linux servers.",
        objective: "Run systemctl status.",
        command: "systemctl",
        hint: "Run systemctl status web.",
        rule: { type: "historyIncludes", command: "systemctl" },
      },
      {
        id: "boss-restart-service",
        title: "Boss Mission: Restart the Service",
        description: "Use systemctl as a recovery command.",
        briefing: "When services fail, operators recover deliberately and verify state.",
        objective: "Run a systemctl command to restart a service.",
        command: "systemctl",
        hint: "Run systemctl restart web.",
        rule: { type: "historyIncludes", command: "systemctl" },
      },
    ],
  },
  {
    levelId: 9,
    commands: networkCommands,
    missions: [
      {
        id: "ping-gateway",
        title: "Ping the Gateway",
        description: "Use ping as a basic connectivity check.",
        briefing: "Network troubleshooting starts with simple reachability checks.",
        objective: "Run ping.",
        command: "ping",
        hint: "Run ping gateway.",
        rule: { type: "historyIncludes", command: "ping" },
      },
      {
        id: "curl-health",
        title: "Check HTTP Health",
        description: "Use curl to check an endpoint.",
        briefing: "curl turns URLs into inspectable terminal output. Health endpoints usually return a tiny status payload for monitoring.",
        objective: "Run curl http://localhost/health to inspect the health endpoint.",
        command: "curl",
        hint: "Run curl http://localhost/health.",
        rule: { type: "historyIncludesExact", command: "curl http://localhost/health" },
      },
      {
        id: "boss-secure-copy",
        title: "Boss Mission: Secure Copy",
        description: "Use scp to simulate transferring an artifact.",
        briefing: "Moving files between systems is a common operator workflow.",
        objective: "Run scp to transfer release.txt.",
        command: "scp",
        hint: "Run scp release.txt server:/tmp/release.txt.",
        rule: { type: "historyIncludes", command: "scp" },
      },
    ],
  },
  {
    levelId: 10,
    commands: automationCommands,
    missions: [
      {
        id: "create-scripts-dir",
        title: "Create a Scripts Directory",
        description: "Organize automation scripts in one place.",
        briefing: "Automation begins with repeatable structure.",
        objective: "Create scripts/.",
        command: "mkdir",
        hint: "Run mkdir scripts.",
        rule: { type: "pathExists", path: "/home/bitbybit/project/scripts", nodeType: "directory" },
      },
      {
        id: "write-backup-script",
        title: "Write a Backup Script",
        description: "Create a simple backup script file.",
        briefing: "Even tiny scripts can encode repeatable operational steps.",
        objective: "Write backup ready into scripts/backup.sh.",
        command: "echo",
        hint: "Run echo \"backup ready\" > scripts/backup.sh.",
        fs: { "/home/bitbybit": { project: { scripts: {} } } },
        rule: { type: "fileContains", path: "/home/bitbybit/project/scripts/backup.sh", text: "backup ready" },
      },
      {
        id: "boss-run-script",
        title: "Boss Mission: Run the Script",
        description: "Use bash to execute an automation script.",
        briefing: "Running scripts safely is the bridge from command user to automator.",
        objective: "Run bash scripts/backup.sh.",
        command: "bash",
        hint: "Run bash scripts/backup.sh.",
        fs: { "/home/bitbybit": { project: { scripts: { "backup.sh": "echo backup ready" } } } },
        rule: { type: "historyIncludes", command: "bash" },
      },
    ],
  },
  {
    levelId: 11,
    commands: automationCommands,
    missions: [
      {
        id: "create-bin-folder",
        title: "Create a Local Bin Folder",
        description: "Prepare a developer command folder.",
        briefing: "Developer workstations often keep scripts and helper binaries in predictable folders.",
        objective: "Create bin/.",
        command: "mkdir",
        hint: "Run mkdir bin.",
        rule: { type: "pathExists", path: "/home/bitbybit/project/bin", nodeType: "directory" },
      },
      {
        id: "write-env-file",
        title: "Write an Environment File",
        description: "Create a small .env file.",
        briefing: "Environment files keep configuration separate from code.",
        objective: "Write APP_ENV=dev into .env.",
        command: "echo",
        hint: "Run echo \"APP_ENV=dev\" > .env.",
        rule: { type: "fileContains", path: "/home/bitbybit/project/.env", text: "APP_ENV=dev" },
      },
      {
        id: "boss-dev-setup",
        title: "Boss Mission: Developer Setup",
        description: "Create a minimal developer workspace.",
        briefing: "A developer environment is useful only when it is reproducible.",
        objective: "Create bin/ and write APP_ENV=dev into .env.",
        command: "mkdir",
        hint: "Run mkdir bin, then echo \"APP_ENV=dev\" > .env.",
        rule: { type: "pathExists", path: "/home/bitbybit/project/bin", nodeType: "directory" },
        extraRule: { type: "fileContains", path: "/home/bitbybit/project/.env", text: "APP_ENV=dev" },
      },
    ],
  },
  {
    levelId: 12,
    commands: automationCommands,
    missions: [
      {
        id: "inspect-broken-server",
        title: "Inspect the Broken Server",
        description: "Read the incident log before changing anything.",
        briefing: "Final recovery starts with evidence, not guesses.",
        objective: "Read incident.log.",
        command: "cat",
        hint: "Run cat incident.log.",
        fs: { "/home/bitbybit": { project: { "incident.log": "ERROR service down\nmissing config" } } },
        rule: { type: "catRead", path: "/home/bitbybit/project/incident.log" },
      },
      {
        id: "restore-config",
        title: "Restore the Config",
        description: "Create the missing config file.",
        briefing: "A missing config can keep an entire service offline.",
        objective: "Write service=enabled into service.conf.",
        command: "echo",
        hint: "Run echo \"service=enabled\" > service.conf.",
        rule: { type: "fileContains", path: "/home/bitbybit/project/service.conf", text: "service=enabled" },
      },
      {
        id: "boss-restore-server",
        title: "Final Boss: Restore the Broken Server",
        description: "Repair config and restart the service.",
        briefing: "This is the full operator loop: inspect, repair, restart, verify.",
        objective: "Create service.conf and run systemctl restart web.",
        command: "systemctl",
        hint: "Run echo \"service=enabled\" > service.conf, then systemctl restart web.",
        fs: { "/home/bitbybit": { project: { "incident.log": "ERROR service down\nmissing config" } } },
        rule: { type: "fileContains", path: "/home/bitbybit/project/service.conf", text: "service=enabled" },
        extraRule: { type: "historyIncludes", command: "systemctl" },
      },
    ],
  },
] as const;

const advancedDebianMissions: MissionDraft[] = advancedMissionSpecs.flatMap((level) =>
  level.missions.map((mission, index) => ({
    id: `debian-l${level.levelId}-${mission.id}`,
    environmentId: "debian",
    levelId: level.levelId,
    title: mission.title,
    description: mission.description,
    briefing: mission.briefing,
    objective: mission.objective,
    difficulty: mission.id.includes("boss") || mission.id.includes("final") ? "boss" : "standard",
    xpReward: mission.id.includes("boss") || mission.id.includes("final") ? 220 : 90 + level.levelId * 5,
    orderIndex: index + 1,
    initialFilesystem: "fs" in mission ? mission.fs : advancedHome,
    startDirectory: "/home/bitbybit/project",
    validationRules: "extraRule" in mission ? [mission.rule, mission.extraRule] : [mission.rule],
    unlockedCommands: level.commands,
    hints: [mission.hint],
    commandName: mission.command,
    badgeReward: mission.id.includes("boss") || mission.id.includes("final") ? badgeForLevel(level.levelId) : undefined,
  }))
);

function badgeForLevel(levelId: number) {
  const badges: Record<number, string> = {
    3: "command-operator",
    4: "log-hunter",
    5: "package-handler",
    6: "package-handler",
    7: "permission-guardian",
    8: "process-controller",
    9: "network-explorer",
    10: "automation-apprentice",
    11: "system-specialist",
    12: "terminal-operator",
  };
  return badges[levelId];
}

const debianMissionDrafts: MissionDraft[] = [
  {
    id: "debian-l1-m1-pwd",
    environmentId: "debian",
    levelId: 1,
    title: "Where Am I?",
    description: "Learn how to ask the shell for your current location.",
    briefing: "Every operator starts by getting oriented. The current working directory tells you where commands will act.",
    objective: "Use pwd to show the current directory.",
    difficulty: "starter",
    xpReward: 40,
    orderIndex: 1,
    initialFilesystem: homeFs,
    startDirectory: "/home/bitbybit",
    validationRules: [{ type: "historyIncludes", command: "pwd" }],
    unlockedCommands: shellCommands,
    hints: ["Type pwd and press Enter."],
  },
  {
    id: "debian-l1-m2-ls",
    environmentId: "debian",
    levelId: 1,
    title: "Look Around",
    description: "List files and folders in the current directory.",
    briefing: "Before changing anything, inspect the room. ls reveals the visible files and folders around you.",
    objective: "Use ls to list files and folders.",
    difficulty: "starter",
    xpReward: 45,
    orderIndex: 2,
    initialFilesystem: homeFs,
    startDirectory: "/home/bitbybit/project",
    validationRules: [{ type: "historyIncludes", command: "ls" }],
    unlockedCommands: shellCommands,
    hints: ["Run ls without arguments."],
  },
  {
    id: "debian-l1-m3-cd-workspace",
    environmentId: "debian",
    levelId: 1,
    title: "Enter the Workspace",
    description: "Move from home into the workspace directory.",
    briefing: "The cd command changes your location. Directories are places you can enter; files are things you read or edit.",
    objective: "Move into the workspace folder.",
    difficulty: "starter",
    xpReward: 55,
    orderIndex: 3,
    initialFilesystem: homeFs,
    startDirectory: "/home/bitbybit",
    validationRules: [{ type: "cwdEquals", path: "/home/bitbybit/workspace" }],
    unlockedCommands: shellCommands,
    hints: ["Use cd workspace."],
  },
  {
    id: "debian-l1-m4-return-home",
    environmentId: "debian",
    levelId: 1,
    title: "Return Home",
    description: "Move up one directory using a relative path.",
    briefing: "Two dots mean the parent directory. Relative movement is the difference between memorizing paths and navigating confidently.",
    objective: "Go back to /home/bitbybit using cd ..",
    difficulty: "starter",
    xpReward: 55,
    orderIndex: 4,
    initialFilesystem: homeFs,
    startDirectory: "/home/bitbybit/workspace",
    validationRules: [{ type: "cwdEquals", path: "/home/bitbybit" }],
    unlockedCommands: shellCommands,
    hints: ["Use cd .. from inside workspace."],
  },
  {
    id: "debian-l1-m5-clear",
    environmentId: "debian",
    levelId: 1,
    title: "Clear the Screen",
    description: "Reset visual clutter while keeping your session alive.",
    briefing: "Real terminals get noisy quickly. clear gives you a clean view without changing files or directories.",
    objective: "Use clear.",
    difficulty: "starter",
    xpReward: 35,
    orderIndex: 5,
    initialFilesystem: homeFs,
    startDirectory: "/home/bitbybit",
    validationRules: [{ type: "historyIncludes", command: "clear" }],
    unlockedCommands: shellCommands,
    hints: ["The command is clear."],
  },
  {
    id: "debian-l1-boss-hidden-folder",
    environmentId: "debian",
    levelId: 1,
    title: "Boss Mission: Find the Hidden Folder",
    description: "Navigate nested folders and reach the secret project directory.",
    briefing: "The academy has buried a flag in a project folder. Inspect, move, and prove you can find your way through a filesystem.",
    objective: "Navigate through folders and reach /home/bitbybit/projects/secret.",
    difficulty: "boss",
    xpReward: 150,
    orderIndex: 6,
    initialFilesystem: {
      "/home/bitbybit": {
        projects: {
          demo: {},
          secret: {
            "flag.txt": "You found the folder.",
          },
        },
        downloads: {},
      },
    },
    startDirectory: "/home/bitbybit",
    validationRules: [{ type: "cwdEquals", path: "/home/bitbybit/projects/secret" }],
    unlockedCommands: shellCommands,
    hints: ["Use ls, cd projects, ls, then cd secret."],
    badgeReward: "shell-awakening",
    avatarItemReward: "shell-glasses",
  },
  {
    id: "debian-l2-m1-project-folder",
    environmentId: "debian",
    levelId: 2,
    title: "Create a Project Folder",
    description: "Create a directory that will hold your first project files.",
    briefing: "mkdir creates directories. Directories organize work and are the backbone of every repository.",
    objective: "Create a folder named project.",
    difficulty: "standard",
    xpReward: 60,
    orderIndex: 1,
    initialFilesystem: blankHome,
    startDirectory: "/home/bitbybit",
    validationRules: [{ type: "pathExists", path: "/home/bitbybit/project", nodeType: "directory" }],
    unlockedCommands: builderCommands,
    hints: ["Run mkdir project."],
  },
  {
    id: "debian-l2-m2-readme",
    environmentId: "debian",
    levelId: 2,
    title: "Create a README",
    description: "Create a Markdown file inside your project directory.",
    briefing: "touch creates an empty file. README files are the entry point for humans reading a project.",
    objective: "Create README.md inside project.",
    difficulty: "standard",
    xpReward: 70,
    orderIndex: 2,
    initialFilesystem: { "/home/bitbybit": { project: {} } },
    startDirectory: "/home/bitbybit",
    validationRules: [{ type: "pathExists", path: "/home/bitbybit/project/README.md", nodeType: "file" }],
    unlockedCommands: builderCommands,
    hints: ["Run touch project/README.md."],
  },
  {
    id: "debian-l2-m3-write-file",
    environmentId: "debian",
    levelId: 2,
    title: "Write Your First File",
    description: "Write text into README.md using echo redirection.",
    briefing: "echo prints text. With >, output is redirected into a file, replacing its contents.",
    objective: "Write \"Hello BitByBit\" into README.md.",
    difficulty: "standard",
    xpReward: 80,
    orderIndex: 3,
    initialFilesystem: { "/home/bitbybit": { project: { "README.md": "" } } },
    startDirectory: "/home/bitbybit/project",
    validationRules: [{ type: "fileContains", path: "/home/bitbybit/project/README.md", text: "Hello BitByBit" }],
    unlockedCommands: builderCommands,
    hints: ["Run echo \"Hello BitByBit\" > README.md."],
  },
  {
    id: "debian-l2-m4-read-file",
    environmentId: "debian",
    levelId: 2,
    title: "Read the File",
    description: "Display README.md in the terminal.",
    briefing: "cat prints file contents. It is simple, direct, and useful when you need a quick read.",
    objective: "Use cat to display README.md.",
    difficulty: "standard",
    xpReward: 65,
    orderIndex: 4,
    initialFilesystem: { "/home/bitbybit": { project: { "README.md": "Hello BitByBit" } } },
    startDirectory: "/home/bitbybit/project",
    validationRules: [{ type: "catRead", path: "/home/bitbybit/project/README.md" }],
    unlockedCommands: builderCommands,
    hints: ["Run cat README.md."],
  },
  {
    id: "debian-l2-boss-workspace",
    environmentId: "debian",
    levelId: 2,
    title: "Boss Mission: Build Your Workspace",
    description: "Create a professional starter workspace layout.",
    briefing: "You have the basics. Build a tiny project skeleton: README, source folder, and docs folder.",
    objective: "Create workspace/ with README.md, src/, and docs/ inside it.",
    difficulty: "boss",
    xpReward: 200,
    orderIndex: 5,
    initialFilesystem: blankHome,
    startDirectory: "/home/bitbybit",
    validationRules: [
      { type: "pathExists", path: "/home/bitbybit/workspace", nodeType: "directory" },
      { type: "pathExists", path: "/home/bitbybit/workspace/README.md", nodeType: "file" },
      { type: "pathExists", path: "/home/bitbybit/workspace/src", nodeType: "directory" },
      { type: "pathExists", path: "/home/bitbybit/workspace/docs", nodeType: "directory" },
    ],
    unlockedCommands: builderCommands,
    hints: ["Use mkdir workspace workspace/src workspace/docs, then touch workspace/README.md."],
    badgeReward: "file-system-builder",
    avatarItemReward: "debian-hoodie",
  },
  ...advancedDebianMissions,
];

export const debianMissions: Mission[] = debianMissionDrafts.map(enrichMission);

const pathNames = {
  debian: [
    "Shell Awakening",
    "File System Builder",
    "Move, Copy, Destroy",
    "Read, Search, Inspect",
    "Archives and Transfers",
    "APT Package Operator",
    "Permissions and Users",
    "Processes and Services",
    "Network Explorer",
    "Bash Automation",
    "Developer Environment Setup",
    "Final Boss: Restore the Broken Server",
  ],
  arch: [
    "Arch Initiate",
    "Filesystem Discipline",
    "Pacman Basics",
    "System Upgrade Discipline",
    "Config Files",
    "Users, Groups, Permissions",
    "Services with systemd",
    "Networking and Mirrors",
    "Shell Power Tools",
    "Bash Scripting",
    "Recovery Mode",
    "Final Boss: Arch Survival Trial",
  ],
  fedora: [
    "Enterprise Shell Basics",
    "Files and Directories",
    "Text Inspection and Logs",
    "DNF Package Management",
    "RPM Awareness",
    "Users, Groups and Sudo",
    "Permissions and Ownership",
    "systemd Services",
    "Networking and Firewall Basics",
    "SELinux Concept Lab",
    "Admin Automation",
    "Final Boss: Enterprise Service Recovery",
  ],
  powershell: [
    "PowerShell Awakening",
    "Files and Folders",
    "Reading and Filtering",
    "PowerShell Objects",
    "Software Management",
    "Processes",
    "Services",
    "Environment Variables and PATH",
    "Networking",
    "Scripting Basics",
    "System Inventory",
    "Final Boss: Windows Admin Rescue",
  ],
  macos: [
    "macOS Shell Basics",
    "Files and Folders",
    "Reading and Searching",
    "Zsh Environment",
    "Homebrew Package Management",
    "Permissions and Executables",
    "Archives and Downloads",
    "Processes",
    "Networking",
    "Shell Scripting",
    "Developer Setup",
    "Final Boss: Mac Developer Setup Rescue",
  ],
};

const makeLevels = (environmentId: keyof typeof pathNames) =>
  pathNames[environmentId].map((title, index) => {
    const missions = environmentId === "debian" ? debianMissions.filter((mission) => mission.levelId === index + 1) : [];
    return {
      id: index + 1,
      title,
      description:
        environmentId === "debian" && missions.length
          ? "Playable mission set with validation, XP, and terminal state."
          : "Curriculum placeholder structured for future mission packs.",
      commands: missions.at(-1)?.unlockedCommands ?? shellCommands,
      missions,
    };
  });

export const environments: EnvironmentPath[] = [
  {
    id: "debian",
    name: "Debian / Ubuntu",
    slug: "debian",
    description: "The beginner-friendly Linux path for developers, operators, and future server rescuers.",
    difficulty: "Beginner",
    isBeginner: true,
    orderIndex: 1,
    initiallyUnlocked: true,
    unlockText: "Available now",
    accent: "#40f5b0",
    levels: makeLevels("debian"),
  },
  {
    id: "powershell",
    name: "Windows PowerShell",
    slug: "powershell",
    description: "Object-oriented Windows administration through a professional shell workflow.",
    difficulty: "Beginner",
    isBeginner: true,
    orderIndex: 2,
    initiallyUnlocked: true,
    unlockText: "Available now",
    accent: "#54d8ff",
    levels: makeLevels("powershell"),
  },
  {
    id: "macos",
    name: "macOS Terminal",
    slug: "macos",
    description: "Zsh, Homebrew, and developer workstation skills for Apple platforms.",
    difficulty: "Beginner",
    isBeginner: true,
    orderIndex: 3,
    initiallyUnlocked: true,
    unlockText: "Available now",
    accent: "#f7c948",
    levels: makeLevels("macos"),
  },
  {
    id: "fedora",
    name: "Fedora / RHEL",
    slug: "fedora",
    description: "Enterprise Linux fundamentals with DNF, RPM awareness, systemd, and SELinux.",
    difficulty: "Intermediate",
    isBeginner: false,
    orderIndex: 4,
    initiallyUnlocked: false,
    unlockText: "Complete Level 6 of any beginner path",
    accent: "#7dd3fc",
    levels: makeLevels("fedora"),
  },
  {
    id: "arch",
    name: "Arch Linux",
    slug: "arch",
    description: "A disciplined power-user path focused on precise system control and recovery.",
    difficulty: "Advanced",
    isBeginner: false,
    orderIndex: 5,
    initiallyUnlocked: false,
    unlockText: "Complete Debian Level 12 or Fedora Level 10",
    accent: "#a78bfa",
    levels: makeLevels("arch"),
  },
];

export const achievements = [
  { id: "shell-awakening", name: "Shell Awakening", description: "Complete the first terminal boss mission.", icon: "Sparkles", xpBonus: 25 },
  { id: "file-system-builder", name: "File System Builder", description: "Build a complete starter workspace.", icon: "FolderTree", xpBonus: 50 },
  { id: "first-command", name: "First Command", description: "Complete your first mission.", icon: "Terminal", xpBonus: 10 },
];

export const avatarItems = [
  "Terminal Hoodie",
  "Shell Glasses",
  "Debian Hoodie",
  "Fedora Jacket",
  "Arch Cape",
  "PowerShell Badge",
  "macOS Zsh Aura",
  "Root Crown",
];

export const getEnvironment = (slug: string) => environments.find((environment) => environment.slug === slug);
export const getMission = (missionId: string) => debianMissions.find((mission) => mission.id === missionId);
